Added support for `--quiet` and `--verbose` flags to `swiftgen run`
SwiftGen/SwiftGen pull request #1008
Opened 2022-08-25 17:59 UTC by jszumski

Fixes https://github.com/SwiftGen/SwiftGen/issues/1007 by extending https://github.com/SwiftGen/SwiftGen/pull/846 to support using `--quiet` and `--verbose` with the `run` command.  If both flags are provided, quiet will override verbose.

2022-08-25 21:33 UTC, luispadron approved these changes
Would love to see this merged, requiring a config for this setting is a bit odd.

2022-08-27 14:16 UTC, djbe requested changes
Look at the `config run` command, there's already a `logLevel` flag that does this. There's no need for 2 separate flags. Reason for this is that these flags are **exclusive** (can't have both).

2022-08-27 17:32 UTC, jszumski commented
> Look at the `config run` command, there's already a `logLevel` flag that does this. There's no need for 2 separate flags. Reason for this is that these flags are **exclusive** (can't have both).

Updated, I didn't realize `CommandLogLevel` would translate directly into multiple flags 💯

2022-08-28 20:50 UTC, djbe approved these changes

2022-08-28 20:50 UTC, merged