Added a 'strings-no-comments-swift3' template. Fixes #222
SwiftGen/SwiftGen pull request #223
Opened 2016-12-04 00:06 UTC by ldiqual

@AliSoftware As per your comment in https://github.com/AliSoftware/SwiftGen/issues/222#issuecomment-264660153

Fixes #222.

 - Added a `strings-no-comments-swift3` template
 - Added a unit test to make sure the output is correct. Output was generated this way:

```
./build/swiftgen/bin/swiftgen strings -t no-comments-swift3 ./UnitTests/fixtures/Localizable.strings -o ./UnitTests/expected/Strings-File-NoComments-Swift3.swift.out
```

 - Added a line in the CHANGELOG

Let me know if you have any question. thanks!

2016-12-04 00:29 UTC, AliSoftware approved these changes

2016-12-04 00:30 UTC, AliSoftware commented
Looks good to me from GitHub at least.
Will merge after the 4.0.1 patch release (as adding a new template is a minor version, not just patch, and will go in upcoming 4.1.0)

2016-12-04 01:41 UTC, AliSoftware requested changes

2016-12-04 01:41 UTC, AliSoftware commented on CHANGELOG.md
> +  [#222](https://github.com/AliSoftware/SwiftGen/issues/222)
I've just released 4.0.1 (while your PR is not part of it) and then merged master into your branch to update your PR… but now your CHANGELOG entry seems to have been merged in the wrong CHANGELOG section :wink: whoops.

Could you please move it to the new `### New Features` subsection **of the `## master` section**?

Thx!

2016-12-05 06:50 UTC, ldiqual commented
@AliSoftware Done.

2016-12-05 08:34 UTC, AliSoftware approved these changes
:+1:

2016-12-05 09:23 UTC, merged