Assets: improve colors performance
SwiftGen/SwiftGen pull request #589
Opened 2019-02-04 19:58 UTC by djbe

Fixes #578.

To use `lazy var`, had to switch to `final class` with our own `init`. This is better than parsing the color during `init` as we can keep the `@availability` annotation for the `color` property.

2019-02-04 20:04 UTC, SwiftGen-Eve commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  5 Markdowns
-->

Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-02-05 00:03 UTC, AliSoftware requested changes

2019-02-05 00:03 UTC, AliSoftware commented on Tests/Fixtures/Generated/XCAssets/swift3-context-all-allValues.swift
> +  internal lazy var color: AssetColorTypeAlias = AssetColorTypeAlias(asset: self)
`private(set)`?

2019-02-05 00:38 UTC, djbe commented on Tests/Fixtures/Generated/XCAssets/swift3-context-all-allValues.swift
> +  internal lazy var color: AssetColorTypeAlias = AssetColorTypeAlias(asset: self)
Good idea.

2019-02-05 00:44 UTC, djbe commented
Rebased with changes from feedback.

2019-02-05 01:47 UTC, AliSoftware approved these changes
LGTM but I'd love for @eaigner to weight in and confirm it fixes the performance issue they observed.

2019-02-05 09:46 UTC, eaigner commented
While I can't speak to the performance aspect right now (the code was changed since i reported the issue), the stencil works.

2019-02-05 11:08 UTC, djbe commented
Could you try it with your local generated code, replacing the `struct` with a `final class`, and the computed `var` by a `lazy var`?

2019-02-05 11:27 UTC, eaigner commented
I have. But I did not benchmark performance. But since its lazy now, should not be a problem, right?

2019-02-07 12:34 UTC, djbe commented
I think it's safe to assume that the `lazy var`s solve the issue. Will merge this PR this evening unless there's more feedback.

2019-02-08 19:44 UTC, merged

2019-03-27 17:44 UTC, eaigner commented
When is 6.2 scheduled to release? Would be nice to have this out there. It's almost 2 months now.

2019-03-27 23:12 UTC, djbe commented
I've been swamped with work these last few weeks, big upcoming release at work.

TBH, things are ready for release, just some final checks and changelog/docs updates (see #621). Maybe this weekend, but I can't promise anything.