Document dependencies #trivial
SwiftGen/SwiftGen pull request #596
Opened 2019-02-08 20:55 UTC by djbe

Saw this blog post and thought it'd be a good idea to document the project's dependencies: http://blog.mazur.me/DEPENDENCIES.md

2019-02-08 20:56 UTC, SwiftGen-Eve commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  5 Markdowns
-->

Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-02-08 22:52 UTC, AliSoftware approved these changes

2019-02-08 22:52 UTC, AliSoftware commented on DEPENDENCIES.md
> +- Added because there's no built-in YAML parser, used for configuration file parsing.
used for parsing the configuration file and for the YAML parser

2019-02-08 22:53 UTC, AliSoftware commented
mmmh wait, I might have approved too quickly 😅 Shouldn't we use the occasion to add a Danger rule that would check if we added (or removed) a Dependency in our Podfile and/or Package.swift, and suggest to update that file in those occasions? Otherwise I fear that we might easily forget to keep that DEPENDENCIES.md up-to-date.

2019-02-08 23:03 UTC, djbe commented
You wanna tackle that one? Your ruby-fu is stronger than mine 😉 

Note: options safety PR coming soon.

2019-02-08 23:56 UTC, AliSoftware commented
Sure. Going to bed rn though and tomorrow will probably be quite busy, will try and take that on Sunday 👍

2019-02-08 23:56 UTC, AliSoftware requested changes
- [x] Danger rule

2019-02-11 15:52 UTC, AliSoftware requested changes

2019-02-11 15:52 UTC, AliSoftware commented on Dangerfile
> +podfile_dependencies = YAML::load_file('Podfile.lock')['SPEC CHECKSUMS'].keys.sort
I think `SPEC CHECKSUMS` might contain checksums of _all_ dependencies, including transitive ones.

In our current state, we don't have many transitive dependencies, and the ones we have (mainly `PathKit` coming from `Stencil` and `Stencil` coming from `StencilSwiftKit`), but imagine if `Kanna` had a dependency to `libXML` and `YAMS` had a dependency to hypothetical `Scanner`, `libYAML` and `Colorize` pods… we shouldn't require to document those, as they'd not be dependencies we chose to add directly, but transitive one coming as dependencies from other pods.

What we might want to document though:

* Dependencies explicitly added in our `Podfile` for SwiftGen-the-tool: we could parse those from the `PODS` key of the `Podfile.lock`, trimming away the version in parentheses to only keep the pod name (another idea would be to run `bundle exec pod ipc podfile Podfile` and parse all the values under any `dependencies` keys in that tree, recursively. But not sure that's worth the effort)
* Dependencies listed in `SwiftGenKit.podspec` as SwiftGenKit is also hosted in this repo and is the core of SwiftGen. We can parse those using `bundle exec pod pic spec SwiftGenKit.podspec` and extract the `dependencies` from the resulting JSON output.

2019-02-11 15:54 UTC, AliSoftware commented on Dangerfile
> +podfile_dependencies = YAML::load_file('Podfile.lock')['SPEC CHECKSUMS'].keys.sort
Also given that the base of those checks are not dependent on GIT and changes made in a PR, but could be run at any time as they compare existing file contents, we might want to move that portion of the code (listing missing dependencies in `DEPENDENCIES.md`) in a `rake` task instead, and in the `Dangerfile` just call that task — but only if the `Podfile.lock` has changed.

2019-02-11 17:52 UTC, djbe commented
👍 

Can't approve 'cause it's my own PR 🤦‍♂️

2019-02-11 18:39 UTC, AliSoftware approved these changes

2019-02-11 18:39 UTC, merged