Improve recommended cocoapod build phase #trivial
SwiftGen/SwiftGen pull request #629
Opened 2019-03-29 03:52 UTC by apptekstudios

Just recommending a simple change to the cocoapods build-phase to prevent errors if there are spaces in directory names.

2019-03-29 03:55 UTC, SwiftGen-Eve commented
<!--
  1 Error: Feature branches should start ...
  0 Warnings
  0 Messages
  6 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Feature branches should start from and be merged into ‘develop’, not master</td>
    </tr>
  </tbody>
</table>

Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Once you fix those tiny nitpickings above, we should be good to go! 🙌

ℹ️ _I will update this comment as you add new commits_

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-04-06 23:46 UTC, djbe requested changes

2019-04-06 23:46 UTC, djbe commented on README.md
> +"${PODS_ROOT}/SwiftGen/bin/swiftgen" …
Could you also update the example at line #60 to match this notation? Would make things more consistent.

2019-04-06 23:47 UTC, djbe commented
Good idea. Just the small nitpick and GTM.

2019-04-07 19:37 UTC, djbe approved these changes

2019-04-07 19:37 UTC, merged