CoreData: Change fetchRequest to createFetchRequest
SwiftGen/SwiftGen pull request #726
Opened 2020-06-23 13:08 UTC by davidrothera

Fixes #725

Technically I can see this as a breaking change so added as such in the `CHANGELOG`

2020-06-23 13:08 UTC, SwiftGen-Eve commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  5 Markdowns
-->

Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Seems like everything is in order 👍 You did a good job here! 🤝

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-06-23 13:17 UTC, djbe requested changes
You'll need to apply the same change to the swift 4 template.

I'm not 100% certain what the naming conventions are, and am very bad at it myself, so unless there's a better suggestion, let's go with `createFetchRequest()`.

2020-06-23 13:17 UTC, djbe commented on CHANGELOG.md
> +  [David Rothera](https://github.com/davidrothera)
Please add a link to the pull request using the same format as other changelog entries.

2020-06-23 13:22 UTC, davidrothera commented
> You'll need to apply the same change to the swift 4 template.
> 
> I'm not 100% certain what the naming conventions are, and am very bad at it myself, so unless there's a better suggestion, let's go with `createFetchRequest()`.

Yeah I'm not sure on whether this is the correct name for the method either, it was either this or `makeFetchRequest` when I was thinking about it.

2020-06-23 22:12 UTC, djbe commented
@davidrothera thx for the quick PR!

Maybe we can avoid this being a breaking change, if we keep the old method name, and add a new method `createFetchRequest()`. We could maybe even add a `@available` annotation marking the old one as deprecated:

```swift
@available(*, deprecated, renamed: "createFetchRequest", message: "To avoid collisions with the less concrete method in `NSManagedObject`, please use `createFetchRequest()` instead.")
@nonobjc internal class func fetchRequest() -> NSFetchRequest<SecondaryEntity> {
  return NSFetchRequest<SecondaryEntity>(entityName: entityName)
}

@nonobjc internal class func createFetchRequest() -> NSFetchRequest< SecondaryEntity > {
  return NSFetchRequest<SecondaryEntity>(entityName: entityName)
}
```

2020-06-23 23:01 UTC, davidrothera commented
> @davidrothera thx for the quick PR!
> 
> Maybe we can avoid this being a breaking change, if we keep the old method name, and add a new method `createFetchRequest()`. We could maybe even add a `@available` annotation marking the old one as deprecated:
> 
> ```swift
> @available(*, deprecated, renamed: "createFetchRequest", message: "To avoid collisions with the less concrete method in `NSManagedObject`, please use `createFetchRequest()` instead.")
> @nonobjc internal class func fetchRequest() -> NSFetchRequest<SecondaryEntity> {
>   return NSFetchRequest<SecondaryEntity>(entityName: entityName)
> }
> 
> @nonobjc internal class func createFetchRequest() -> NSFetchRequest< SecondaryEntity > {
>   return NSFetchRequest<SecondaryEntity>(entityName: entityName)
> }
> ```

Thanks for the suggestion, yeah I would always prefer not having to break backwards compatibility. I'll get this changed shortly 👍

2020-06-23 23:12 UTC, davidrothera commented
I've added the method back in along with a deprecation notice, I updated the `CHANGELOG` to move it to the "New Features" section but not sure whether it would be best there or under one of the other headings.

2020-06-23 23:49 UTC, djbe requested changes
So we also need to update:
- swift 4 docs
- readme usage example code
- playgrounds page code

2020-06-23 23:49 UTC, djbe commented on Documentation/templates/coredata/swift5.md
> -  @nonobjc internal class func fetchRequest() -> NSFetchRequest<MainEntity> {
Please also make these changes in the swift 4 docs.

2020-06-23 23:51 UTC, djbe commented
Changelog location is ok for now, we can always move it later if really needed.

2020-06-28 15:36 UTC, davidrothera commented
Hey @djbe, have you had chance to look over the latest changes you requested?

2020-07-04 19:39 UTC, djbe commented
Allright, seems like those last changes cover everything.

One unfortunate bit is that I read through the API design guidelines:
> Begin names of factory methods with “make”, e.g. x.makeIterator().

So it should become `makeFetchRequest()` 😅 Luckily, we can find/replace now that the initial effort is done.
Feel free to rebase your commits if you find that easier.

2020-07-04 20:00 UTC, davidrothera commented
Good find and nice to know, there are probably some places in my own code which I should clean up in that case as well 😝

2020-07-04 21:05 UTC, davidrothera commented
Ok should be good to go now @djbe

2020-07-05 00:01 UTC, djbe approved these changes
Nice, thx for the update!

I'm approving this now, but not merging it yet, as we still need to release 6.2.1. Depending on how that release goes, we may need a 6.2.2. After all that, this can be merged for 6.3.0.

2020-07-06 21:07 UTC, merged