Release 6.3.0
SwiftGen/SwiftGen pull request #758
Opened 2020-08-02 19:20 UTC by AliSoftware

Let's get those new stringsdict features out!

2020-08-02 19:27 UTC, SwiftGen-Eve commented
<!--
  0 Errors
  1 Warning: You should make sure that <cod...
  1 Message: This is a Release PR
  10 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should make sure that <code>Podfile.lock</code> and <code>Package.resolved</code> are changed in sync</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This is a Release PR</td>
    </tr>
  </tbody>
</table>

Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

### ChangeLog check

✅  All entries seems OK (end with period + 2 spaces, correct links)


### Release version check

| Check                                         | Status       |
| --------------------------------------------- | ------------ |
| Bundler installed                             | ✅           |
| SwiftGen.podspec                              | 👉  6.3.0    |
| SwiftGenKit.podspec                           | 👉  6.3.0    |
| SwiftGen & SwiftGenKit versions equal         | ✅           |
| SwiftGen-Info.plist version matches           | ✅           |
| SwiftGenKit-Info.plist version matches        | ✅           |
| StencilSwiftKit up-to-date (latest: 2.7.2)    | ✅           |
| CHANGELOG: Release entry added                | ✅           |
| CHANGELOG: No develop entry                   | ✅           |
| README: pod version ~> 6.0                    | ✅           |


Once you fix those tiny nitpickings above, we should be good to go! 🙌

ℹ️ _I will update this comment as you add new commits_

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-08-02 20:19 UTC, djbe requested changes
Changes here all look OK, a couple of things we may want to update while we're creating a release:
- [x] Mint installation instructions: remove `brew install libxml2`
- [x] Changelog entries for `bundle` & `lookupFunction`: point to dedicated article about these.
- [x] Maybe a small template migration guide entry for the font typealias deprecation? We did write a tiny entry in contexts for the `documents` change in 6.2.1

2020-08-03 01:05 UTC, djbe approved these changes

2020-08-03 02:13 UTC, AliSoftware commented on Documentation/templates/MigrationGuide.md
> +In the `fonts` templates, we're deprecating the generated `Font` typealias. So if you were using it somewhere in your own code, create your own typealias, or use the platform sepcific type such as `U
```suggestion
In the `fonts` templates, we're deprecating the generated `Font` typealias. So if you were using it somewhere in your own code, create your own typealias, or use the platform-specific type such as `UIFont`/`NSFont`. The `Font` typealias will be removed in the next major release of SwiftGen.
```

2020-08-04 21:29 UTC, merged

2020-08-04 22:01 UTC, AliSoftware commented
```
--------------------------------------------------------------------------------
 :tada:  Congrats

 :rocket:  SwiftGen (6.3.0) successfully published
 :date:  August 5th, 00:00
 :earth_americas:  https://cocoapods.org/pods/SwiftGen
 :+1:  Tell your friends!
--------------------------------------------------------------------------------
```

2020-08-04 22:27 UTC, AliSoftware commented
Pending PR in Homebrew: https://github.com/Homebrew/homebrew-core/pull/59153