Support `instantiateViewController(identifier:creator:)` for ib templates
SwiftGen/SwiftGen pull request #778
Opened 2020-09-25 16:03 UTC by matsune

templates

* [x] I've started my branch from the `develop` branch (gitflow)
  * [x] And I've selected `develop` as the "base" branch for this Pull Request I'm about to create
* [ ] I've added an entry in the `CHANGELOG.md` file to explain my changes and credit myself  
      _(or added `#trivial` to the PR title if I think it doesn't warrant a mention in the CHANGELOG)_
  * [ ] Add the entry in the appropriate section (Bug Fix / New Feature / Breaking Change / Internal Change)
  * [ ] Add a period and 2 spaces at the end of your short entry description
  * [ ] Add links to your GitHub profile to credit yourself and to the related PR and issue after your description

---
[`instantiateViewController(identifier:creator:)`](https://developer.apple.com/documentation/uikit/uistoryboard/3213989-instantiateviewcontroller#declaration) is now avaliable to create a view controller since iOS 13 (and OSX also has a similar method).
This allows us to inject dependencies into the view controller using storyboard, and I think SwiftGen default templates could support this.
If you intend to merge this change, I'll add an entry to changelog.

2020-09-25 16:05 UTC, SwiftGen-Eve commented
<!--
  1 Error: Please include a CHANGELOG ent...
  1 Warning: Big PR
  0 Messages
  7 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry to credit your work.  <br />
You can find it at <a href="https://github.com/matsune/SwiftGen/blob/feature/instantiate-creator/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

Hey 👋 I'm Eve, the friendly bot watching over SwiftGen 🤖

Thanks a lot for your contribution!



---

Once you fix those tiny nitpickings above, we should be good to go! 🙌

📝 We use the following format for CHANGELOG entries:
```
* Support `instantiateViewController(identifier:creator:)` for ib templates.  
  [#778](https://github.com/SwiftGen/SwiftGen/pull/778)
  [@matsune](https://github.com/matsune)
```
:bulb: Don't forget to end the line describing your changes by a period and two spaces.


ℹ️ _I will update this comment as you add new commits_

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-02 17:59 UTC, djbe requested changes

2020-10-02 17:59 UTC, djbe commented on templates/ib/scenes-swift4.stencil
> +      .__instantiate{{controller}}(withIdentifier: identifier, creator: block) as? T else {
Why the `__` for AppKit? From what I can see in the docs, the method has no `__`.

2020-10-02 17:59 UTC, djbe commented on templates/ib/scenes-swift4.stencil
> +      .__instantiate{{controller}}(withIdentifier: identifier, creator: block) as? T else {
I don't think a `guard` with `as` cast is needed? The new `instantiate` methods are generic, and Swift should be able to infer the type to be `T`. So I think the code should just be what you have for non-appkit platforms, namely:

```swift
return storyboard.storyboard.instantiate{{controller}}(identifier: identifier, creator: block)
```

2020-10-02 17:59 UTC, djbe commented on templates/ib/scenes-swift4.stencil
> +    guard let controller = storyboard.storyboard
Same as above, I don't think a `guard` is needed? (and same comment about `__`)

2020-10-04 21:39 UTC, djbe commented
@matsune I've taken the liberty of finishing up this PR. It should work, but you can take a look at it if you want.
I'll probably merge this in a day or 2 if there's no more feedback.

2020-10-04 21:39 UTC, SwiftGen-Eve commented on CHANGELOG.md
> +* IB: Added support for instantiating scenes while providing a `creator` block, commonly used for dependency injection. This feature is available starting from iOS 13, tvOS 13 and macOS 10.15.
<table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/SwiftGen/SwiftGen/blob/9998c51351f6384bd7524010e61558cb9cf44506/CHANGELOG.md#L23"></span>Line describing your entry should end with a period and 2 spaces.</td>
    </tr>
  </tbody>
</table>

2020-10-04 21:41 UTC, djbe approved these changes

2020-10-05 02:40 UTC, matsune commented
@djbe Thank you for your review & fixing my PR!
I have no problem to merge this.

2020-10-05 10:13 UTC, merged