Make generated CoreData model class final when model isn't abstract
SwiftGen/SwiftGen pull request #940
Opened 2022-05-18 23:33 UTC by grsouza

Change Core Data Swift 5 template for adding support to set a class as `final` when the model isn't abstract.

2022-06-03 13:22 UTC, grsouza commented
What you guys think about this? @djbe and @AliSoftware

2022-07-20 23:12 UTC, djbe commented on Sources/SwiftGenCLI/templates/coredata/swift5.stencil
> +{% set final %}{% if entity.isAbstract %}{% else %}final {% endif %}{% endset %}
Avoid setting a property if you're only going to use it once, especially for for simple checks.

2022-07-20 23:14 UTC, djbe commented on Sources/SwiftGenCLI/templates/coredata/swift5.stencil
> +{{ accessModifier }} {{ final }}class {{ entityClassName }}: {{ superclass }} {
```suggestion
{{ accessModifier }} {% if not entity.isAbstract %}final {% endif %}class {{ entityClassName }}: {{ superclass }} {
```

2022-07-20 23:15 UTC, djbe requested changes
Good idea. I've added some comments on your changes.

Also note that this change needs to also be made for the other templates (`swift4` in this case), and generate the output as well for those.

2022-07-21 09:02 UTC, grsouza commented
Hey, @djbe I noticed that you already made the changes. Is there anything that still needs to be handled?

2022-07-21 13:52 UTC, djbe commented
I was waiting for the tests to finish, and they curiously enough revealed an error. In our tests we have:
- A `MainEntity`, which is *not* abstract
- A `ChildEntity`, which has `MainEntity` as a parent

You can create this situation in the model editor. I have no idea how useful it is, or valid, but it's possible. Hence, we have to handle it gracefully.

2022-07-21 14:15 UTC, djbe commented
There, that should solve it. Had to resolve to a trick in Stencil to check if something exists in an array 😅

2022-07-21 14:45 UTC, djbe approved these changes

2022-07-21 14:45 UTC, merged